### PR TITLE
Back off to using curl if wget fails on freemarker checksum (macos)

### LINKED ISSUE #1194: mac builds failing on certificate check on www.apache.org for freemarker
```
--2019-07-30 04:29:14--  https://www.apache.org/dist/freemarker/engine/2.3.28/binaries/apache-freemarker-2.3.28-bin.tar.gz.asc
Resolving www.apache.org... 95.216.24.32, 40.79.78.1, 2a01:4f9:2a:185f::2
Connecting to www.apache.org|95.216.24.32|:443... connected.
ERROR: cannot verify www.apache.org's certificate, issued by ‘CN=Sectigo RSA Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
To connect to www.apache.org insecurely, use `--no-check-certificate'.
```

### PR DESCRIPTION
**Pull request by sxa555**
Fixes #1194 

Signed-off-by: Stewart Addison <sxa@uk.ibm.com>

### CODE REVIEW

File: sbin/prepareWorkspace.sh [hunk 1]
```diff
@@ -238,7 +238,8 @@ checkingAndDownloadingFreemarker()
   else
 
     wget -nc --no-check-certificate "https://www.mirrorservice.org/sites/ftp.apache.org/freemarker/engine/${FREEMARKER_LIB_VERSION}/binaries/apache-freemarker-${FREEMARKER_LIB_VERSION}-bin.tar.gz"
-    wget "https://www.apache.org/dist/freemarker/engine/${FREEMARKER_LIB_VERSION}/binaries/apache-freemarker-${FREEMARKER_LIB_VERSION}-bin.tar.gz.asc"
+    wget "https://www.apache.org/dist/freemarker/engine/${FREEMARKER_LIB_VERSION}/binaries/apache-freemarker-${FREEMARKER_LIB_VERSION}-bin.tar.gz.asc" ||
```
Comment (karianna) [inline sbin/prepareWorkspace.sh]: Why would curl succeed when wget fails?

Comment (karianna) [reply sbin/prepareWorkspace.sh]: Ah, I see, can you add a comment in that case as to why?

Comment (sxa555) [reply sbin/prepareWorkspace.sh]: Done - reference to the issue included
