### PR TITLE
Pass in build jdk repo and branch to test pipeline builds

### LINKED ISSUE #1674: Triage corretto jdk8u/jdk11u xlinux sanity.openjdk test failures
Corretto has its own test pipelines now, see the top-level targets that are launched at the end of these build pipelines:

------

jdk11u:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-corretto/27/console

sanity.system : passes
extended.system : passes
sanity.perf (running as functional tests) : passes
sanity.openjdk : [10 test cases](https://ci.adoptopenjdk.net/job/Test_openjdk11_corretto_sanity.openjdk_x86-64_linux/2/testReport/) failing 

------

jdk8u:
sanity.system : passes
extended.system : passes
special.functional : passes
sanity.openjdk : [7 test cases](https://ci.adoptopenjdk.net/job/Test_openjdk8_corretto_sanity.openjdk_x86-64_linux/1/testReport/) failing 

Need to triage the test failures, identify which are already reported and report any new ones to the correct repo for fixing.

### PR DESCRIPTION
**Pull request by sophia-guo**
Fix #1674 

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

File: pipelines/build/common/openjdk_build_pipeline.groovy [hunk 1]
```diff
@@ -110,13 +110,25 @@ class Build {
 
     def runTests() {
         def testStages = [:]
-        List testList = []
-
+        List testList = buildConfig.TEST_LIST
+        def java_to_build = buildConfig.JAVA_TO_BUILD
+        jdk_branch = 'dev'
```
Comment (karianna) [inline pipelines/build/common/openjdk_build_pipeline.groovy:115]: could jdk_branch be declared as a def or static type?

Also `dev` is the Adopt default branch, I think we should explicitly call that out

File: pipelines/build/common/openjdk_build_pipeline.groovy [hunk 2]
```diff
@@ -110,13 +110,25 @@ class Build {
...
+        suffix="adoptopenjdk/openjdk-${java_to_build}"
```
Comment (karianna) [inline pipelines/build/common/openjdk_build_pipeline.groovy:116]: could suffix be declared as a def or static type?

File: pipelines/build/common/openjdk_build_pipeline.groovy [hunk 3]
```diff
@@ -110,13 +110,25 @@ class Build {
 
     def runTests() {
         def testStages = [:]
-        List testList = []
-
+        List testList = buildConfig.TEST_LIST
+        def java_to_build = buildConfig.JAVA_TO_BUILD
```
Comment (karianna) [inline pipelines/build/common/openjdk_build_pipeline.groovy:114]: Groovy naming convention is camelCase

File: pipelines/build/common/openjdk_build_pipeline.groovy [hunk 4]
```diff
@@ -110,13 +110,25 @@ class Build {
...
+            suffix="corretto/corretto-${java_number}"
+        } else if (buildConfig.VARIANT == "openj9") {
+            jdk_branch = 'openj9'
+            suffix = "ibmruntimes/openj9-openjdk-jdk${java_number}"
         }
+        
+        jdk_repo = "https://github.com/${suffix}"
+        if (buildConfig.BUILD_ARGS.include("--ssh")) {
+			jdk_repo = "git@github.com:${suffix}"
+		}
```
Comment (karianna) [inline pipelines/build/common/openjdk_build_pipeline.groovy:130]: whitespace seems out

File: pipelines/build/common/openjdk_build_pipeline.groovy (hunk 1 above)
Comment (sophia-guo) [reply pipelines/build/common/openjdk_build_pipeline.groovy]: Updated.

File: pipelines/build/common/openjdk_build_pipeline.groovy (hunk 2 above)
Comment (sophia-guo) [reply pipelines/build/common/openjdk_build_pipeline.groovy]: Updated.

File: pipelines/build/common/openjdk_build_pipeline.groovy (hunk 3 above)
Comment (sophia-guo) [reply pipelines/build/common/openjdk_build_pipeline.groovy]: Updated.

File: pipelines/build/common/openjdk_build_pipeline.groovy (hunk 4 above)
Comment (sophia-guo) [reply pipelines/build/common/openjdk_build_pipeline.groovy]: Updated. Thanks!

File: pipelines/build/common/openjdk_build_pipeline.groovy [hunk 5]
```diff
@@ -110,13 +110,26 @@ class Build {
 
     def runTests() {
         def testStages = [:]
-        List testList = []
-
+        List testList = buildConfig.TEST_LIST
```
Comment (karianna) [inline pipelines/build/common/openjdk_build_pipeline.groovy:113]: Sorry to keep nitpicking here, but can some of this be extracted into small private functions?  It seems that we're doing a setJDKBranch() and a setJDKRepo()...

Comment (sophia-guo) [reply pipelines/build/common/openjdk_build_pipeline.groovy]: Thanks @karianna! Instead of doing a set***() I prefer to do a get***().  As tests are actually getting those information from build parameters.

**Comment by karianna** [comment]
@sophia-guo That's really nice and clean now - thanks for the rework
